[workspace]
members = [
    "unsafe_rust",
    "external_rust",
    "global_rust",
    "advanced_traits",
    "advanced_types",
    "macros",
    "hello_macro",
    "hello_macro/hello_macro_derive",
]
